apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "14.6-alpine-cron"
spec:
  coordinator:
    image: kubedb/pg-coordinator:v0.13.0
  db:
    baseOS: alpine
    image: kubedb/postgres:14.6-alpine-cron
  distribution: Official
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.9.0
  initContainer:
    image: kubedb/postgres-init:0.5.0
  podSecurityPolicies:
    databasePolicyName: postgres-db
  securityContext:
    runAsAnyNonRoot: false
    runAsUser: 70
  stash:
    addon:
      backupTask:
        name: postgres-backup-14.0
      restoreTask:
        name: postgres-restore-14.0
  version: "14.6"
