apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: 13.2-postgis
spec:
  coordinator:
    image: kubedb/pg-coordinator:v0.6.0
  db:
    image: kubedb/postgres:13.2-postgis
  distribution: PostgreSQL
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.9.0
  initContainer:
    image: kubedb/postgres-init:0.3.0
  podSecurityPolicies:
    databasePolicyName: postgres-db
  securityContext:
    runAsAnyNonRoot: true
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: postgres-backup-13.1
      restoreTask:
        name: postgres-restore-13.1
  version: "13.2"
