apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "15.3-alpine-tds-fdw"
spec:
  coordinator:
    image: ghcr.io/kubedb/pg-coordinator:v0.18.0
  db:
    baseOS: alpine
    image: ghcr.io/kubedb/postgres:15.3-alpine-tds_fdw
  distribution: KubeDB
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.9.0
  initContainer:
    image: ghcr.io/kubedb/postgres-init:0.7.0
  podSecurityPolicies:
    databasePolicyName: postgres-db
  securityContext:
    runAsAnyNonRoot: false
    runAsUser: 70
  stash:
    addon:
      backupTask:
        name: postgres-backup-15.1
      restoreTask:
        name: postgres-restore-15.1
  updateConstraints:
    allowlist:
    - "14.2"
  version: "15.3"
