apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: 13.2-alpine-pg-audit
spec:
  coordinator:
    image: kubedb/pg-coordinator:v0.10.0
  db:
    image: kubedb/postgres:13.2-alpine-pgaudit
  distribution: PostgreSQL
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.9.0
  initContainer:
    image: kubedb/postgres-init:0.4.0
  podSecurityPolicies:
    databasePolicyName: postgres-db
  securityContext:
    runAsAnyNonRoot: false
    runAsUser: 70
  stash:
    addon:
      backupTask:
        name: postgres-backup-13.1
      restoreTask:
        name: postgres-restore-13.1
  version: "13.2"
