apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: 11.11-pgsqueeze
spec:
  coordinator:
    image: kubedb/pg-coordinator:v0.6.0
  db:
    image: kubedb/postgres:11.11-pgsqueeze
  distribution: PostgreSQL
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.9.0
  initContainer:
    image: kubedb/postgres-init:0.3.0
  podSecurityPolicies:
    databasePolicyName: postgres-db
  securityContext:
    runAsAnyNonRoot: true
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: postgres-backup-11.9
      restoreTask:
        name: postgres-restore-11.9
  version: "11.11"
