apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  labels:
    app: kubedb
  name: "11.16-pg-cron"
spec:
  db:
    image: kubedb/postgres:11.16-pg-cron
  exporter:
    image: kubedb/postgres_exporter:v0.4.7
  podSecurityPolicies:
    databasePolicyName: postgres-db
    snapshotterPolicyName: postgres-snapshot
  tools:
    image: kubedb/postgres-tools:11.2
  version: "11.16"
