apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: demo-postgis
  namespace: demo
spec:
  version: "13.2-postgis"
  replicas: 3
  standbyMode: Hot
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut

