apiVersion: kubedb.com/v1
kind: Postgres
metadata:
  name: demo-pg-vector
  namespace: demo
spec:
  version: "16.8-pgvector"
  replicas: 3
  standbyMode: Hot
  storageType: Durable
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  deletionPolicy: WipeOut
