apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: demo-tds-fdw
  namespace: default
spec:
  version: "15.3-alpine-tds-fdw"
  replicas: 3
  standbyMode: Hot
  storageType: Durable
  storage:
    storageClassName: "linode-block-storage"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
